# -*- coding: utf-8 -*-
"""plot_f1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16CwJhT6rKd2MdE-k6Du_9GVveh9ybF0k
"""

import matplotlib.pyplot as plt
import pandas as pd

plt.figure(figsize=(12, 10))
df = pd.read_csv('adaboost.csv')

plt.errorbar(x=range(len(df)), y=df['F1'], yerr=df['std'], fmt='o', color='black', capsize=5)
plt.xticks(range(len(df)), df['Dataset'], rotation=45, ha='right')

plt.title('F1 Scores by Dataset with Standard Deviation for LogidBoost')
plt.ylabel('F1 Score')
plt.xlabel('Dataset')

plt.gca().invert_xaxis()
plt.tight_layout()
plt.show()