# -*- coding: utf-8 -*-
"""plot_f1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16CwJhT6rKd2MdE-k6Du_9GVveh9ybF0k
"""

import matplotlib.pyplot as plt
import pandas as pd
def plot_f1_score(file_path):

  plt.figure(figsize=(10, 8))
  df = pd.read_csv(file_path)

  plt.errorbar(x=range(len(df)), y=df['F1'], yerr=df['std'], fmt='o', color='grey', capsize=5)
  plt.xticks(range(len(df)), df['Dataset'], rotation=45, ha='right')

  plt.title('F1 Scores by Dataset with Standard Deviation for LogidBoost')
  plt.ylabel('F1 Score')
  plt.xlabel('Datasets')

  plt.gca().invert_xaxis()
  plt.tight_layout()
  plt.show()

#for baseline
file_path = 'logidboost_baseline.csv'
plot_f1_score(file_path )