# -*- coding: utf-8 -*-
"""plot_f1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16CwJhT6rKd2MdE-k6Du_9GVveh9ybF0k
"""

import matplotlib.pyplot as plt
import pandas as pd
def plot_f1_score(file_path):

  plt.figure(figsize=(10, 8))
  df_base = pd.read_csv('adaboost_baseline.csv')
  df = pd.read_csv(file_path)

  plt.errorbar(x=range(len(df_base)), y=df_base['F1'], yerr=df_base['std'], fmt='o', color='grey', capsize=5, label='Baseline')
  #for your csv file
  #adjust color
  plt.errorbar(x=range(len(df_base)), y=df['F1'], yerr=df['std'], fmt='o', color='grey', capsize=5, label='Base enstimators')
  plt.xticks(range(len(df_base)), df_base['Dataset'], rotation=45, ha='right')

  plt.title('F1 Scores by Dataset with Standard Deviation for AdaBoost')
  plt.ylabel('F1 Score')
  plt.xlabel('Datasets')
  plt.legend(fontsize='12')
  plt.gca().invert_xaxis()
  plt.tight_layout()
  plt.show()

#how to use
#file_path = '/your_path'
#plot_f1_score(file_path)
